development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://<%= ENV['REDIS_SERVER'] %>:<%= ENV['REDIS_PORT'] %>/<%= ENV['REDIS_CABLE_DATABASE'] %>
  channel_prefix: <%= ENV["REDIS_CACHE_NAMESPACE"] %>

production:
  adapter: redis
  url: redis://<%= ENV['REDIS_SERVER'] %>:<%= ENV['REDIS_PORT'] %>/<%= ENV['REDIS_CABLE_DATABASE'] %>
  channel_prefix: <%= ENV["REDIS_CACHE_NAMESPACE"] %>
